In [1]:
import pandas as pd
from sklearn import preprocessing
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

df = pd.read_csv('CustomerData.csv')
df = df.bfill()
encoder = preprocessing.LabelEncoder()
df[['category', 'purchase type ', 'gender']] = df[['category', 'purchase type ', 'gender']].apply(encoder.fit_transform)
df.head()

features = df[['age', 'gender', 'annual income (lakhs)']]
target = df['purchase type ']
x_train, x_test, y_train, y_test = train_test_split(features, target, random_state = 0, test_size = 0.3)


from sklearn.cluster import KMeans

dataframe = df[['gender', 'age', 'category']]

kmeans = KMeans(n_clusters = 5, random_state = 0)
kmeans.fit_predict(dataframe)
print("Cluster centers\n", kmeans.cluster_centers_)
dataframe['cluster'] = kmeans.labels_

Cluster centers
 [[ 0.64285714 55.14285714  7.21428571]
 [ 0.69230769 18.76923077  6.38461538]
 [ 0.88888889 31.11111111 13.        ]
 [ 1.          5.16666667  8.5       ]
 [ 0.33333333 41.          5.66666667]]


/home/umer/.local/lib/python3.6/site-packages/ipykernel_launcher.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [2]:
dataframe.head()

gender   age  category  cluster
0       0  53.0         1        0
1       1  53.0         5        0
2       1  22.0         5        1
3       1   9.0        12        3
4       1  55.0        12        0